CC = gcc 
MAKE = make
LIBPATH = ../../src/.libs
INCPATH = ../../src
BIN = pll
PLL = pll
ARCH = SSE3-PTHREADS
LIBRARIES = -lpll-sse3 -lm -lpthreadGC2 -L/mingw/lib/x86
TARGET = $(BIN)-$(ARCH)
RM = rm -f

$(BIN)-$(ARCH): main.c
	@echo "==> Building PLL example ($(BIN)-$(ARCH))"
	$(CC) -DHAVE_CONFIG_H -D_USE_PTHREADS -I. -I../.. -I../../src -g -O0 -DNON_POSIX -DPLLDEBUG -DPLL_DEBUG_MESSAGES $+ -L $(LIBPATH) -I $(INCPATH) $(LIBRARIES) -o $@ 

clean : 
	-$(RM) $(BIN)-$(ARCH)

.PHONY: all clean
